### ISSUE TITLE
Stripe error

### ISSUE THREAD

**Issue by Opswatch** [alexisbouchez/proustai#2]
Looks like its now getting a stripe error even though in .env strip is commented out.

` Stripe: Argument "customer" must be a string, but got: null (on API request to `GET /v1/customers/{customer}`)
    request_id: "oaehgvn2o6ushcppqo6v7ubp"
    x-request-id: "oaehgvn2o6ushcppqo6v7ubp"
    err: {
      "type": "Error",
      "message": "Stripe: Argument \"customer\" must be a string, but got: null (on API request to `GET /v1/customers/{customer}`)",
      "stack":
          Error: Stripe: Argument "customer" must be a string, but got: null (on API request to `GET /v1/customers/{customer}`)
              at file:///home/ops/ops/proustai/node_modules/stripe/esm/StripeResource.js:96:23
              at Array.reduce (<anonymous>)
              at Constructor._getRequestOpts (file:///home/ops/ops/proustai/node_modules/stripe/esm/StripeResource.js:93:35)
              at file:///home/ops/ops/proustai/node_modules/stripe/esm/StripeResource.js:141:29
              at new Promise (<anonymous>)
              at Constructor._makeRequest (file:///home/ops/ops/proustai/node_modules/stripe/esm/StripeResource.js:137:16)
              at Constructor.retrieve (file:///home/ops/ops/proustai/node_modules/stripe/esm/StripeMethod.js:28:67)
              at BillingService.retrieveCurrentBillingPeriod (/home/ops/ops/proustai/app/services/billing_service.ts:16:46)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at ChaptersController.complete (/home/ops/ops/proustai/app/controllers/chapters_controller.ts:87:34)
      "status": 500
    }`

It also outputs the error into the main editor in the webpage instead of just a log. 

Im running the latest master and deleted and rebuilt the containers just to be sure.

**Comment by alexisbouchez** [comment]
Fixed in this commit, thanks again for reporting https://github.com/alexisbouchez/proustai/commit/d8202a3efcf788692468f2f1f4a3482a8f77612a
